#@ load("@ytt:assert", "assert")
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#@ def velero_installer():
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-installer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-installer
subjects:
- kind: ServiceAccount
  name: velero-installer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: velero-installer
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: installer
        image: harbor.terasky.demo/tkg-crs/tkg-131-helper:v0.1.0
        command: ["/bin/sh"]
        args:
          - -c
          - #@ "/install-velero.sh {} {} {} {} {}".format( data.values.S3_BUCKET_NAME, data.values.S3_BUCKET_REGION, data.values.S3_URL, data.values.S3_ACCESS_KEY, data.values.S3_SECRET_KEY)
      restartPolicy: Never
      serviceAccountName: velero-installer
  backoffLimit: 4
#@ end

#@ if data.values.INSTALL_VELERO and data.values.TKG_CLUSTER_ROLE == "workload":
#@overlay/match by=overlay.subset({"kind":"KubeadmControlPlane"})
---
spec:
  #@overlay/match-child-defaults missing_ok=True
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          feature-gates: RemoveSelfLink=false
#@ end
#@ if data.values.INSTALL_VELERO and data.values.TKG_CLUSTER_ROLE == "workload":
---
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: #@ "{}-velero-deployment".format(data.values.CLUSTER_NAME)
  labels:
    cluster.x-k8s.io/cluster-name: #@ data.values.CLUSTER_NAME
spec:
  strategy: "ApplyOnce"
  clusterSelector:
    matchLabels:
      tkg.tanzu.vmware.com/cluster-name: #@ data.values.CLUSTER_NAME
  resources:
  - name: #@ "{}-velero-deployment".format(data.values.CLUSTER_NAME)
    kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ "{}-velero-deployment".format(data.values.CLUSTER_NAME)
data:
  data: #@ yaml.encode(velero_installer())
#@ end
