#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def tkg_extensions():
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tkg-extensions-installer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tkg-extensions-installer
subjects:
- kind: ServiceAccount
  name: tkg-extensions-installer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tkg-extensions-installer
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: installer
        image: #@ data.values.TKG_HELPER_IMAGE_REF
        command: ["/bin/sh"]
        args:
          - -c
          - #@ "/install-extensions.sh {} {} {} {} {} {} {} {} {} {}".format( data.values.GRAFANA_PASSWORD, data.values.GRAFANA_FQDN, data.values.MGMT_CLUSTER_NAME, data.values.CLUSTER_NAME, data.values.VRLI_FQDN, data.values.VRLI_PORT, data.values.VRLI_PROTOCOL, data.values.VRLI_FORMAT, data.values.DNS_SERVER, data.values.DNS_ZONE)
      restartPolicy: Never
      serviceAccountName: tkg-extensions-installer
  backoffLimit: 4
#@ end


#@ if data.values.ENABLE_TKG_EXTENSIONS and data.values.TKG_CLUSTER_ROLE == "workload":
---
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: #@ "{}-tkg-extension-stack".format(data.values.CLUSTER_NAME)
  labels:
    cluster.x-k8s.io/cluster-name: #@ data.values.CLUSTER_NAME
spec:
  strategy: "ApplyOnce"
  clusterSelector:
    matchLabels:
      tkg.tanzu.vmware.com/cluster-name: #@ data.values.CLUSTER_NAME
  resources:
  - name: #@ "{}-tkg-extensions".format(data.values.CLUSTER_NAME)
    kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ "{}-tkg-extensions".format(data.values.CLUSTER_NAME)
data:
  data: #@ yaml.encode(tkg_extensions())
  #@ end
