apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: zookeeper.bitnami.charts
spec:
  displayName: "zookeeper"
  longDescription: "Bitnami zookeeper 3.7.0 - Helm Chart version 7.4.6"
  shortDescription: "zookeeper Version 3.7.0"
  categories:
  - bitnami
  - helm
