#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name":"grafana"}}),expects=1
---
spec:
  type: #@ (data.values.monitoring.grafana.service.type or "ClusterIP")
