apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: airflow.bitnami.charts
spec:
  displayName: "airflow"
  longDescription: "Bitnami airflow 2.1.4 - Helm Chart version 11.1.1"
  shortDescription: "airflow Version 2.1.4"
  categories:
  - bitnami
  - helm
