---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: prometheus
spec:
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.27.0+vmware.1-tkg.1
      prereleases: {}
  serviceAccountName: tkg-packages-sa
